name: Generate Snake Animation

on:
  schedule: # Run at 1 AM UTC every day
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Datas Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      # Snake Animation
      - name: Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: deveshjoshi101
          outputs: dist/snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
