name: Generate Datas

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # execute every 12 hours

jobs:
  build:
    name: Update Datas Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Snake Animation
      - name: Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: deveshjoshi101
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
